### ISSUE TITLE
Only HSQLDB?

### ISSUE THREAD

**Issue by BlackRule** [cuba-platform/sample-user-registration#3]
If I change db to postgresql clicking on register new user I get acess denied. What's wrong?

**Comment by BlackRule** [comment]
It seems I solved it manually executing:
INSERT INTO SEC_ROLE VALUES('3ec31528-dc0e-c341-7727-7b46771ae9ff','2016-11-20 23:11:35.000000','u1',2,NULL,NULL,NULL,NULL,'Users',NULL,NULL,TRUE,0);
INSERT INTO SEC_PERMISSION VALUES('a01617a7-080d-1a6d-c820-b55874147afa','2018-06-21 15:26:46.000000','admin',1,'2018-06-21 15:26:46.000000',NULL,NULL,NULL,10,'register-screen',1,'cd541dd4-eeb7-cd5b-847e-d32236552fa9');
INSERT INTO SEC_PERMISSION VALUES('bc1d9ee1-8689-a4f5-e1da-aade690252e2','2018-06-21 15:39:55.000000','admin',1,'2018-06-21 15:39:55.000000',NULL,NULL,NULL,20,'sec$User:update',1,'cd541dd4-eeb7-cd5b-847e-d32236552fa9');
INSERT INTO SEC_PERMISSION VALUES('bc5a4446-3254-051b-a20a-46e1e2d26314','2018-06-21 15:31:13.000000','admin',1,'2018-06-21 15:31:13.000000',NULL,NULL,NULL,10,'restore-password-screen',1,'cd541dd4-eeb7-cd5b-847e-d32236552fa9');
INSERT INTO SEC_PERMISSION VALUES('f27a9f6c-8ca9-8e8a-2f72-34e854a5cc09','2018-06-21 15:37:32.000000','admin',1,'2018-06-21 15:37:32.000000',NULL,NULL,NULL,20,'sec$User:read',1,'cd541dd4-eeb7-cd5b-847e-d32236552fa9');
on my postgresql Please fix it

**Comment by BlackRule** [comment]
Please simply tell me how do I migrate HSQL db to postgesql. I need it urgently..

**Comment by jreznot** [comment]
See the answer here: https://www.cuba-platform.com/discuss/t/how-to-set-up-user-registration-sample-with-postgresql/6047

Please note, that we do not answer questions on Github. Use our discussion forum instead. Github issues is used only for bugs in sample source code.
